plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
<<<<<<< HEAD
  - name: infura
=======
  - name: ape-infura
>>>>>>> bcb939b (feat: add infura config)

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.5.0
  - name: vault
    github: yearn/yearn-vaults
    version: 0.4.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.5.0"

ethereum:
  local:
    default_provider: hardhat
    